# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:8.2.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: 'npm install -g node-gyp'
      - run:
          name: rebuild node-gyp
          command: 'node-gyp rebuild'
      - save_cache:
          paths:
            - ./node_modules
          keys: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run tests
          command: 'echo done'
