# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:8.0.0
    working_directory: ~/repo
    steps:
      - checkout
      # - run:
      #     name: update-npm
      #     command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: rm node_modules
      #     command: 'npm rm'
      - run:
          name: npm install
          command: 'sudo npm install -g node-gyp'
      - run:
          name: show folder
          command: 'ls -la'
      - run:
          name: rebuild node-gyp
          command: 'sudo node-gyp rebuild'
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run tests
          command: 'echo done'
